### ISSUE TITLE
macdonell dictionary  - distinguish multiple meanings better.

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit#27]
Once upon a time paper and books were costly, and entries were compact.
So, we have for hari:
> हरि hár-i, a. [√ 3. hṛ, be yellow] tawny, yellow (esp. of horses); greenish (rare, C.); m. (C.) steed (sp. of Indra); lion; monkey; N. of Indra and (more commonly) of Viṣṇu-kṛṣṇa; N. of a various men; (hári)- keśa, a. tawny-haried; -gaṇa, m. troop of horses; N.; -ghoṣa, m. N.; -candana, m. (?) Indra's sandal tree (one of the five trees in Indra's paradise); kind of sandal tree; n. yellow sandal; -candra, m. N.; -cāpa, m. n. Indra's bow, rainbow.

Now, we don't have similar constraints and can help the reader by putting different meanings in:
* separate dict entries (clean and ideal - I know that you'd need to do some special tricks to combine hari-candra type words) 
* separate bullet point (an ok intermediate state one can arrive at by splitting based on ;).

**Comment by drdhaval2785** [comment]
Comma seems to be selarator in this dictionary for new meaning.

**Comment by vvasuki** [comment]
Well, in the above example, it seems to be semicolon - ;

**Comment by drdhaval2785** [comment]
Intended to say semi colon..

**Comment by funderburkjim** [comment]
This kind of parsing (to ferret out sub-headwords, for instance)  is challenging.  Not impossible, of course, but difficult due to irregularities.   If @drdhaval2785  wants to attempt, I would suggest that the goal be to introduce xml markup first.  Then render the xml markup as appropriate for stardict.

**Comment by gasyoun** [comment]
> I would suggest that the goal be to introduce xml markup first

If @vvasuki is interested, let him try first :+1:  Dhaval will get lost if he starts to, because every dictionary is so different. The idea is great, but it should be possible to regenerate the files at any time later.

**Comment by drdhaval2785** [comment]
@funderburkjim

Right now the goal for me is to reap low hanging fruits as of now. The betterment can come later. Right now offerring dictionaries in some presentable way is the goal. Some compromise is acceptable in terms of quality.

XML markup change is something serious, because it will affect all kinds of displays. Need to do it with 100% accuracy and devotion. Dont intend to handle it right now.

**Comment by funderburkjim** [comment]
Regarding xml changes and stardict.

Since you are basing the stardict conversions on the xxx.xml form of the Cologne dictionaries,
your conversion programs might need to be modified if there is a change to the xxx.dtd.  

Yours is about the first serious 'downstream' project to the Cologne dictionaries, so there is no
developed procedure for communicating 'upstream' changes (e.g. to xxx.dtd) to you.  We'll have to
keep this potential problem in mind if and when any changes are made to any dictionary dtd's.

**Comment by vvasuki** [comment]
> Since you are basing the stardict conversions on the xxx.xml form of the Cologne dictionaries,
your conversion programs might need to be modified if there is a change to the xxx.dtd.
> Yours is about the first serious 'downstream' project to the Cologne dictionaries, so there is no
developed procedure for communicating 'upstream' changes (e.g. to xxx.dtd) to you.

The only downstream communication to this project right now seems to be through updated babylon files. Or @drdhaval2785 , do you intend to place your conversion scripts here? Where are they right now?

**Comment by drdhaval2785** [comment]
The only downstream communication to this project right now seems to be
through updated babylon files. Or @drdhaval2785
<https://github.com/drdhaval2785> , do you intend to place your conversion
scripts here?


Yes I do. In fact, I intend to create a shell script redo.sh which will
fetch latest XML from cologne servers and regenerate all necessary files
for us. We cab run the shell script once a month and sync our dicts.

Where are they right now?

On a local computer. Some structural changes need to be made before putting
them here or somewhere else.

**Comment by vvasuki** [comment]
>  In fact, I intend to create a shell script redo.sh which will
fetch latest XML from cologne servers and regenerate all necessary files
for us.

Good that you mentioned it! Speaking from experience, avoid shell script - 
* as logic gets complicated, bash code is uglier.
* you can call shell commands from any high level language (including python).

**Comment by drdhaval2785** [comment]
Scripts are at https://github.com/sanskrit-lexicon/cologne-stardict. And the separators are now handled for most of the entries, so that subheadwords appear on next line.

**Comment by drdhaval2785** [comment]
![screenshot_20190210-092321_colordict](https://user-images.githubusercontent.com/5755132/52529335-e0c3c400-2d15-11e9-9b1e-2da19960656f.jpg)
