### ISSUE TITLE
Use normalized headwords to increase access

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#66]
This is trigerred by observation of @vvasuki regarding SKD. There are differences in conventions of different dictionaries. https://github.com/sanskrit-lexicon/hwnorm1/blob/master/ejf/hwnorm1c/hwnorm1c.txt provides some insight into headword normalization. Apply to all dictionaries to improve coverage. This will inflate file size though.

**Comment by vvasuki** [comment]
Splendid plan!

**Comment by vvasuki** [comment]
But be a bit careful. I suggest that for now you add prAtipadika-s to dictionaries giving out the declined form, but not the other way round - because some entries of some dictionaries list multiple linga-s within the same entry. In such a case, splitting the entry and matching with the appropriate declined form makes far more sense.

Example:
![image](https://cloud.githubusercontent.com/assets/2664797/25112131/1e259954-23a4-11e7-8b60-3bcf8f2f7e34.png)

**Comment by drdhaval2785** [comment]
It seems too difficult to tag properly declined items for alternate
headwords. A start has already been made, but it will not reach logical
conclusion soon. https://github.com/sanskrit-lexicon/alternateheadwords is
the place where we track such discussion.

**Comment by gasyoun** [comment]
> now you add prAtipadika-s to dictionaries

I'm against. hwnorm1c.txt, inveted by @drdhaval2785 is about being universal. If 4 out of 30 dictionaries have them, that means we should have bare roots and word, but not wordforms. By the example you wanted to show we would not find `manas` or what, @vvasuki ?

**Comment by vvasuki** [comment]
> It seems too difficult to tag properly declined items for alternate
headwords.

Indeed. But there should be no problems adding roots (for the most part), right @drdhaval2785 ? Even adding it for common forms like terms ending with visarga and makaara would help a great deal.

>> now you add prAtipadika-s to dictionaries

> I'm against. hwnorm1c.txt, inveted by @drdhaval2785 is about being universal. If 4 out of 30 dictionaries have them, that means we should have bare roots and word, but not wordforms.

That's contradictory and funny, because you are agreeing that we should definitely have "roots" (= prAtipadika-s in case of nouns). :-) 

As to wordforms (a separate issue) - sure, we should add those too (when we have the capability), to help users. I've often dermined the proper grammatical gender of words quickly by seeing if the appropriate (karNaH vs karNam) declension appears in the auto-complete list in the dictionary app.

**Comment by drdhaval2785** [comment]
Added the alternate headwords according to latest hwnorm1c file. One way.
Imflected forms convrted to base and not vice versa.

This makes a part of general make_babylon.py program. So should update with
each revision of hwnorm1c in future.

Pending to upload. Waiting for all corrections to be over before uploading
something on release.

**Comment by gasyoun** [comment]
> Pending to upload. Waiting for all corrections to be over before uploading
something on release.

Years ahead?

**Comment by drdhaval2785** [comment]
@vvasuki and @gasyoun 
This is now done in #99
